services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb+srv://root:verysecretpassword@db/user?retryWrites=true"
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    restart: always
    user: mongo
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: verysecretpassword
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
